/**
 * speechapi
 * Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveImageApiClient);
  }
}(this, function(expect, CloudmersiveImageApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveImageApiClient.SpeechRecognitionResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SpeechRecognitionResult', function() {
    it('should create an instance of SpeechRecognitionResult', function() {
      // uncomment below and update the code to test SpeechRecognitionResult
      //var instane = new CloudmersiveImageApiClient.SpeechRecognitionResult();
      //expect(instance).to.be.a(CloudmersiveImageApiClient.SpeechRecognitionResult);
    });

    it('should have the property textResult (base name: "TextResult")', function() {
      // uncomment below and update the code to test the property textResult
      //var instane = new CloudmersiveImageApiClient.SpeechRecognitionResult();
      //expect(instance).to.be();
    });

  });

}));
